### ISSUE TITLE
ParseExcpetion: checked Exception vs RuntimeException

### ISSUE THREAD

**Issue by gtrefslp** [ok2c/httpclient-migration-guide#1]
Hi Oleg,

thank you very much for the migration guides. I am currently migrating an application using httplient 4.5.x to httpclient5. The code uses `EntityUtils#toString(HttpEntity)` to parse the response body to text. During the migration, I discovered that `ParseException` was made a checked exception compared to being a `RunTimeException` before. This forces me to take of the exception. Was this an intended changed? Do you know why?

Best regards,
Gregor

**Comment by ok2c** [comment]
@gtrefslp Malformed or invalid messages is a protocol level issue.  `ParseException` was made a subclass of `ProtocolException` to reflect that.

**Comment by gtrefslp** [comment]
Thanks for the explanation. This makes sense. If you don't mind, I have another question in regards of the new `BasicHttpRequest#getUri` vs. the old `HttpRequestBase#getURI`. `BasicHttpRequest#getUri` throws an `URISyntaxException` while `BasicHttpRequest#getUri` did not. In the new code, a given URI is deconstructed into its components (scheme, authority, etc.) while in the old it was not and then created from these components again upon request. However, I find it a bit odd, that it is now possible to create a request which potentially has a malformed URI. In the old code this was not possible. Why was this changed?

Further, `URIAuthority` converts the the host to all lower case while the old `HttpRequestBase` preserved the letter case. This leads to a change in behaviour. Here is a little example:

```Java
URI uri = URI.create("http://someAddress/path");
HttpPost post = new HttpPost(mtlsForwardEndpointUri);
URI uriFromPost = post.getUri();
uri.equals(uriFromPost); // false because host was converted to lower case someaddress
``` 
Was this change intended?

**Comment by ok2c** [comment]
>  given URI is deconstructed into its components (scheme, authority, etc.)

This is required by the HTTP/2 specification.

> that it is now possible to create a request which potentially has a malformed URI.

It was always possible. There are users who for various reasons want to be able to submit requests with a malformed URI path component.

> Was this change intended?

Yes, it was. It was fully intentional. HttpClient normalizes and in some cases even rewrites request URIs.

**Comment by gtrefslp** [comment]
Thanks again for the explanation and the effort you put into the project.
